version: '3'
services:
  frontend:
    build: ./FrontEnd/autocomplete
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./BackEnd/graphql-server
    ports:
      - "4000:4000"
